### ISSUE TITLE
Are share-extras available in any Maven repository? 

### ISSUE THREAD

**Issue by krzysztofdrys** [share-extras/js-console#27]
I am building my alfresco using Maven. I am using a few items from share-extra. I would like to be able to build my alfresco automatically (as opposed to manually downloading and installing appropriate jar's/amp's). So, are share-extras available in any Maven repository? Are there any plans for doing so?

**Comment by jgoldhammer** [comment]
I would like to push this topic after such a long time...

I have changed the 0.6 pre prelease to a production release.
Is that Ok? CC: @wabson @fmaul @AFaust

**Comment by igorbga** [comment]
Any progress with this ? I'm going to upload the AMP as an artifact in our own nexus repo but it would be great if the javascript console would be published somewhere.

By the  way, in its latest SDK's Alfresco itself is pushing its artifacts to central so maybe using central instead of alfresco's nexus for Share Extras should be something to consider.

**Comment by wabson** [comment]
I have created an account on Alfresco's Nexus which can be used for automatically publishing Share Extras builds there. I would prefer if the deploy was automatic from the build env rather than by hand by the developer, can you think of a way for us to do this?

**Comment by igorbga** [comment]
I'm a newbie with maven myself but wouldn't something like what they
explain in this blogpost be enough?

https://support.sonatype.com/entries/21283268-Configure-Maven-to-Deploy-to-Nexus

Bye


2015-04-19 11:49 GMT+02:00 Will Abson <notifications@github.com>:

**Comment by jgoldhammer** [comment]
@wabson we have a travis build now.
https://travis-ci.org/share-extras/js-console

How can make an automatic deploy?

Thanks,
Jens

**Comment by wabson** [comment]
It looks to me like Travis could be configured to push automatically to artifacts.alfresco.com. Is that what you mean?

I looked in the `pom.xml` and I see there is a `<distributionManagement>` section in there but it does not contain any details, only some property refs. The details for the [share-extras](https://artifacts.alfresco.com/nexus/content/repositories/share-extras/) repo would need to be configured there, and you also need to define a `settings.xml` on an orphan branch or a remote webserver that Travis can pull in, which act as a placeholder for the credentials, which I can populate.

The Travis docs were not helpful but I found two [blog](https://vzurczak.wordpress.com/2014/09/23/deploying-to-maven-repositories-from-tavis-ci/) [posts](https://coderwall.com/p/9b_lfq/deploying-maven-artifacts-from-travis) which document this fairly well.

If you want to create a ticket for the work and see how far you get then I can take the last part of configuring some environment variables in Travis for the Nexus username and password.

**Comment by mindthegab** [comment]
Hey guys, I can help here maybe.

This is a very common request (just got yesterday from Bindu @ Zia at the Alfresco days), so whatever i can do to help, let me know.

Let me know!

**Comment by douglascrp** [comment]
How about making this part of the core?

Em qua, 5 de ago de 2015 às 15:25, mindthegab <notifications@github.com>
escreveu:

**Comment by mindthegab** [comment]
@douglascrp Why would you do that? 

The whole point we are trying to push in Alfresco (with release agility, proper APIs, etc) it's modularization, not keep on shoveling everything in the same humangous unreleaseable monolith. 

Also this is a community project, so bringing into core would have support implications and I don't really see the advantage now.

Let's just make sure it's available out there in a standard way (Maven repo), so that people can just use a <dependency> or a puppet / chef script to retrieve.

This issue is about deployment, so I suggest you open a separate one (and probably in the Alfresco JIRA, not github) if you want to discuss / elaborate on why you think this should be in core. Pretty confusing to mix all sort of different requests in the same thread, I am sure you can imagine how many different threads we deal with on a daily basis.

Thanks!

**Comment by douglascrp** [comment]
I understand your point.

Em qua, 5 de ago de 2015 às 15:31, mindthegab <notifications@github.com>
escreveu:

**Comment by jgoldhammer** [comment]
Hi @wabson  and @mindthegab , 

can you help me to make js-console available on artifacts.alfresco.com?
What are the next steps for me and you?

Thanks,
Jens

**Comment by wabson** [comment]
Hi Jens, did you see my [comment](https://github.com/share-extras/js-console/issues/27#issuecomment-121285154) above? If you agree with my suggestions and a pull request along those lines came my way then I'm sure I could get some appropriate credentials configured in Travis and test it all out.

**Comment by fmaul** [comment]
The Javascript Console AMP files are now in Maven Central. See the README for the info on how to include it in your POM files.
